#SPDX-License-Identifier: MIT-0
---
- name: Restart victoriametrics
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: victoriametrics
    state: restarted
    enabled: true

